### ISSUE TITLE
Blog 2.0

### ISSUE THREAD

**Issue by magarcia** [magarcia/magarcia.github.io#3]
**TODO:**
- [x] Support old jekyll posts
- [x] Pagination support
- [x] Medium like style
- [x] Fix gist integration
- [x] Fix statics
- [ ] ~~Crosspost to medium~~ #5
- [x] Deploy script
- [ ] ~~RSS support~~ #4
- [x] Post actions (eg: share via tweet, etc)
